### ISSUE TITLE
pdm backend support?

### ISSUE THREAD

**Issue by Lawouach** [carstencodes/pdm-bump#101]
Hello @carstencodes,

I might be wrong but it looks like dynamic versioning requires BUILD_BACKEND_PDM_PEP517_API only. However this backend is now deprecated by pdm so I was wondering if you had a plan to also support pdm backend?

Thanks,

**Comment by carstencodes** [comment]
Hi, 

I didn't notice the retirement of this backend, but I think this not very unlikely. I'm currently thinking of dropping this restriction, but I have no tight schedule yet.

**Comment by Lawouach** [comment]
No worries. It seems though that the newer backend offers that bump facility natively. When running `pdm build` with an `scm` dynamic version. Might be worth checking when you have time :)

**Comment by carstencodes** [comment]
@Lawouach Just releasing 0.7.1

It requires PDM 2.7.4 or later (cf. #104). Please note, that PDM bump cannot be executed, if the version is fetched from SCM.
