### ISSUE TITLE
PDM Bump cannot be executed with PDM > 2.7.1

### ISSUE THREAD

**Issue by carstencodes** [carstencodes/pdm-bump#104]
A breaking change has taken place.

Refer to https://github.com/pdm-project/pdm/issues/2009 for details.

**Comment by frostming** [comment]
Hi, this is fixed in 2.7.3 and installing the latest version should work fine.

**Comment by carstencodes** [comment]
Unit tests are failiing in https://github.com/carstencodes/pdm-bump/actions/runs/5254290456/jobs/9492709629?pr=105

**Comment by carstencodes** [comment]
A Bugfix will be added soon
