### ISSUE TITLE
docs: `pdm bump micro` typo

### ISSUE THREAD

**Issue by themattmorris** [carstencodes/pdm-bump#135]
Thank for you creating this tool!

Hey I just noticed this in the documentation:

https://github.com/carstencodes/pdm-bump/blob/6b20ed43c98e5451971a4b57bc6d85f9dfceaf1a/README.md?plain=1#L37

I believe this should read:

```
$ pdm bump micro # creates 0.1.1
```

(`0.1.1` vs `0.1.2`), considering the initial version in the example was `0.1.0`.

If you agree, lemme know, and I can submit a PR if needed.

**Comment by carstencodes** [comment]
Yeah, exactly, it shows a sequence of commands.

So, the idea will be that `0.1.1rc1` will be followed by `0.1.1` and the `micro` command will result in `0.1.2`.

Maybe I should clarify this somehow in the comments.

**Comment by carstencodes** [comment]
Ok, I'll see, what I can do.
