### ISSUE TITLE
Feature request - Alternate pre release specifiers

### ISSUE THREAD

**Issue by Flowake** [carstencodes/pdm-bump#201]
Hello,

Thanks for this package which is very useful to work with. I'm using it at work to handle versioning across our python packages in a monorepo. I had to write some scripts to handle a monorepo using this tool, but it was fairly simple using the -p option from pdm.

There are only two issues that required me to go after the changes made by pdm-bump to my version files:

- Handle pre-releases for micro/minor/major versions (I think most of the work has been done to handle it like poetry, but I couldn't make it work with the 0.8.0 pre-releases)
- Handle separators for pre-releases: right now, a pre-release will be in the form of 1.0.0a1 for alpha 1, but other valid representation would be 1.0.0-alpha.1. I have tools that do not consider the first one to be valid.

For the first issue, when do you think the 0.8.0 will be released with the premicro, preminor, premajor option ? For the second one, I'm willing to make a PR for supporting this kind of syntax using CLI args.

**Comment by carstencodes** [comment]
Hi,

> * Handle pre-releases for micro/minor/major versions (I think most of the work has been done to handle it like poetry, but I couldn't make it work with the 0.8.0 pre-releases)

Ok, can you please provide me the issue? What did not work?

> * Handle separators for pre-releases: right now, a pre-release will be in the form of 1.0.0a1 for alpha 1, but other valid representation would be 1.0.0-alpha.1. I have tools that do not consider the first one to be valid.

This library targets PEP440 as it is the format, pip, pypi, poetry etc are using. Other formats might actually disturb the toolchains and are hence not really target of this library.
With revision 0.9.0, I can actually try to create a namespace package for this, so this can be customized.

> For the first issue, when do you think the 0.8.0 will be released with the premicro, preminor, premajor option ? 

I am currently hoping to release it within the course of next week.

> For the second one, I'm willing to make a PR for supporting this kind of syntax using CLI args.

May we can discuss the use case first in this. It will actually require a new parser and a new formatter.

**Comment by Flowake** [comment]
Thanks for your quick reply.

In my case, I'm using both Python and Rust, so I wanted to use the same versioning scheme, and Rust only supports specifying pre releases as "1.0.0-alpha.1" for example. "1.0.0a1" would not work, but upon reading PEP440 again, this syntax is not supported by Python, so that would not make much sense to include it in this tool.

For the new commands "premicro", "preminor" and "premajor", if I install pdm and pdm-bump 0.8.0a2 in a fresh environement, they do not seem to be accessible, or maybe I'm using it wrong.

**Comment by carstencodes** [comment]
Sorry for the late response, but due to a flu I was not able to do anything.

> For the new commands "premicro", "preminor" and "premajor", if I install pdm and pdm-bump 0.8.0a2 in a fresh environement, they do not seem to be accessible, or maybe I'm using it wrong.

Could you please enter the results of `pdm bump` and `pdm -vv bump`?

**Comment by carstencodes** [comment]
@Flowake Before publishing 0.8.0, can you please confirm, that the issue is still at hand?

**Comment by Flowake** [comment]
I will check this tomorrow and make you know if I can reproduce it, but I think it was working and it was just an issue between the global pdm and the virtual environment in which I was installing the plugin.

**Comment by carstencodes** [comment]
@Flowake Have you been able to reproduce the issue?

**Comment by Flowake** [comment]
I tried again and it seems I had an issue with the PDM installed system wide and the one installed in the venv I was testing in.

I think you can close this issue, thanks for your reactivity.

**Comment by carstencodes** [comment]
Great to hear.
