### ISSUE TITLE
Feature request: `-g` or `--git-tag`

### ISSUE THREAD

**Issue by lmmx** [carstencodes/pdm-bump#219]
I've been making Python packages over the Christmas break with the `pyo3` Rust crate's _extension module_ feature, and just found [the `cargo-bump` plugin][1] which fills a missing piece of my Python release workflow: a `-g`/`--git-tag` flag to immediately commit the bumped version & create a git tag, which you can then release on GitHub

```
FLAGS:
    -g, --git-tag    Commits the new version and creates a git tag
...
```

I think this would work really well with `pdm-bump` (in fact I came here to file this feature request immediately! :smiley:)

[1]: https://github.com/wraithan/cargo-bump

**Comment by carstencodes** [comment]
@lmmx I'm currently working on that, but in the first place it will only commit the new version. Adding the tag will be a good extension to that. I'm not very faithful, that this will be released this year.

**Comment by lmmx** [comment]
Sweet! Great minds think alike :smiley: 

I've taken a look at the approach taken in cargo-bump and outlined it below for your reference, along with a Python implementation. Happy to work these into a PR if you'd prefer that.

## Rust approach

```rust
    let use_git = conf.git_tag;
    if use_git {
        git::git_check();
    }
```

1. If `config.use_git` argument is true/truthy, run `git_check` from the git module (runs `git status --porcelain`)
  - raise if it fails and advise user to "install git and try again"
  - error if output is empty as it means the working directory is not clean and advise user to "Please commit changes before trying to update the version"

2. edit the version string in the package code (in Rust this is in Cargo.toml, pdm-bump has already figured this part out), store the version that was bumped to

```rust
    let output = update_toml_with_version(&raw_data, conf.version_modifier);
    let version = output["package"]["version"].as_str().unwrap();
```

3. Git commit and tag the stored version
  - Try: `git commit -am ${version}`
    - Except: raise an error with the message "Something went wrong trying to commit the new version"
  - Try: `git tag -am ${version} ${version}`
    - Except: raise an error with the message "Something went wrong when creating a git tag"

```rust
    if use_git {
        git::git_commit_and_tag(version);
    }
```

from:

```rust
pub fn git_tag(version: &str) {
    Command::new("git")
        .args(&["tag", "-am", version, version])
        .status()
        .expect("Something went wrong when creating a git tag.");
}

pub fn git_commit(version: &str) {
    Command::new("git")
        .args(&["commit", "-am", version])
        .status()
        .expect("Something went wrong trying to commit the new version.");
}

pub fn git_commit_and_tag(version: &str) {
    git_commit(version);
    git_tag(version);
}
```

## Python implementation

Here is the code to do this in Python:

```py
import subprocess

def git_check() -> None:
    try:
        result = subprocess.check_output(['git', 'status', '--porcelain'])
        if result:
            raise RuntimeError("Working directory is not clean. Please commit changes before trying to update the version.")
    except subprocess.CalledProcessError:
        raise RuntimeError("This tool requires git. Please install git and try again.")

def update_version_in_file(version_modifier: str) -> str:
    ... # Implement your logic to update the version string here
    return new_version

def git_commit(version: str) -> None:
    try:
        subprocess.check_call(['git', 'commit', '-am', version])
    except subprocess.CalledProcessError:
        raise RuntimeError("Something went wrong trying to commit the new version.")
    return

def git_tag(version) -> None:
    try:
        subprocess.check_call(['git', 'tag', '-am', version, version])
    except subprocess.CalledProcessError:
        raise RuntimeError("Something went wrong when creating a git tag.")
    return

def git_commit_and_tag(version) -> None:
    git_commit(version)
    git_tag(version)
    return
```

So the main routine code would be:

```py
use_git = conf.git_tag
if use_git:
    git_check()

new_version = update_version_in_file(conf.version_modifier)

if use_git:
    git_commit_and_tag(new_version)
```

**Comment by carstencodes** [comment]
If you take a look at the current implementation, we're almost there:

The existing command

```shell
$ pdm bump suggest
...
```

will analyze you're git history and suggest a new semantic version based on your conventional commits.

On one of the branches a proposal for `pdm bump auto` is implemented, which takes the suggestion and create commit from this.

Finally, the existing command

```shell
$ pdm bump tag
...
```

will create a tag.

Hence, all I have to do is add the ability to evaluate the tag.

This could be done in the base implementation of `VersionModifier` at https://github.com/carstencodes/pdm-bump/blob/6979f3062fd2b0c5d5c667e2e0ad561cd0b073aa/src/pdm_bump/actions/base.py#L243

I think, this won't take much effort. All I have to do is create a pre- and post handling of the command.

I will come back to you in the next 2 days.

**Comment by carstencodes** [comment]
@lmmx Feel free to play around with it in 0.8.0b1

**Comment by carstencodes** [comment]
Please note, the command is --tag or -t
