### ISSUE TITLE
Configuration issues

### ISSUE THREAD

**Issue by SmileyChris** [carstencodes/pdm-bump#284]
The readme says add `[tools.pdm.bump_plugin]`  to `pyproject.toml`, but that doesn't actually work.

Firstly, because your prefix is actually `tool.pdm.bump-plugin`, and secondly because local pdm configuration happens in `pdm.toml`.

As a separate point, look at other settings in `pdm config`: the configuration prefixes of `tool.pdm` is redundant -- you could just use `bump-plugin` (or even just `bump`?).

**Comment by carstencodes** [comment]
Hi,

die to PI plannings, I'm currently pretty busy. 

I Hope that I will be able to have a look at it within the next days.

**Comment by carstencodes** [comment]
Hi @SmileyChris,

I'm sorry, this slept through so much.

I confess that I wrote the configuration part some time ago, when the pdm.toml contained the path to the local python interpreter and was not a good subject to be checked in. So, I decided to put it all into the pyproject.toml. 

I plan to fix it in one of the coming versions.

**Comment by carstencodes** [comment]
Scheduled for pdm-bump 0.10.0 mid of august
