### ISSUE TITLE
Bug? Bump pre-release from released version

### ISSUE THREAD

**Issue by znichollscr** [carstencodes/pdm-bump#326]
Thanks @carstencodes for your great work on this!

I'm getting the following output

```
pdm bump pre-release --pre alpha
Performing increment of version: 0.5.2 -> 0.5.2a1
```

Is this behaviour intended? I would have thought that, if I am on version 0.5.2 and I bump to the next pre-release, I should go to 0.5.3a1 (i.e. the pre-release for the next version) rather than 0.5.2a1 (which would be a pre-release for a version which has already been released, namely 0.5.2).

**Comment by carstencodes** [comment]
I thought, that I had fixed this. I'll take a look at it over the course of the weekend.

**Comment by znichollscr** [comment]
Ah I didn't look on latest main, so I might just be using the wrong version

**Comment by carstencodes** [comment]
The [default](https://github.com/carstencodes/pdm-bump/blob/3a00f81c8e7eb25e40096c8dd0797957b9bc449a/src/pdm_bump/actions/preview.py#L63) is at least set to `True`.

**Comment by carstencodes** [comment]
And depends on [whether it is a pre-release](https://github.com/carstencodes/pdm-bump/blob/3a00f81c8e7eb25e40096c8dd0797957b9bc449a/src/pdm_bump/actions/preview.py#L201) or not.

**Comment by carstencodes** [comment]
> Ah I didn't look on latest main, so I might just be using the wrong version
@znichollscr 
Is it working with a newer version?

**Comment by znichollscr** [comment]
Hmm no still appears unhappy. I'll do some digging now

**Comment by carstencodes** [comment]
As there are two more bugs to go, I would implement them first before releasing a new version. Is that ok for you?

**Comment by znichollscr** [comment]
> Is that ok for you?

Yep no rush at all.
