### ISSUE TITLE
`pdm bump` removes comments from `pyproject.toml`

### ISSUE THREAD

**Issue by znichollscr** [carstencodes/pdm-bump#327]
I've noticed that running `pdm bump` removes any comments that are in my `pyproject.toml`. That isn't the end of the world, but it might be a good thing to document. I'm happy to write a PR that adds that, I just wanted to check two questions:

1. Is the re-write of `pyproject.toml` deliberate?
2. Is there an easy way to avoid it, or is preserving comments really difficult?

**Comment by carstencodes** [comment]
Currently, the data is parsed into a dictionary using tomli or tomllib. Than tomli-w writes the data back.

The comments are not preserved during parsing.

I have to rework the pyproject.toml handling anyway, I can take care of it in the next days.

**Comment by carstencodes** [comment]
I could update this, so that pyproject.toml is a special case of dynamic. Would take a bit. Hopefully sunday...
