### ISSUE TITLE
Error bumping in CI/CD

### ISSUE THREAD

**Issue by alexanderepstein** [carstencodes/pdm-bump#347]
I use pdm bump in a gitlab pipeline and a new issue has arisen when running pdm bump. 

```
[AttributeError]: '_PdmPep517StorageBackend' object has no attribute '_DynamicStorageBackend__config'
```

I have updated pdm to the latest version along with the lock file and the issue still persists.

**Comment by carstencodes** [comment]
Hi, can you try version 0.9.8?

**Comment by alexanderepstein** [comment]
That resolved it, thanks @carstencodes for the quick turnaround! :smile:

**Comment by carstencodes** [comment]
You're Welcome.
