### ISSUE TITLE
Dynamic version support?

### ISSUE THREAD

**Issue by gazpachoking** [carstencodes/pdm-bump#6]
So I'm guessing the answer is just 'no', but I was wondering if there was any way to work with dynamic versioning? Specifically, updating the version in a file like `__init__.py` or `__version__.py` I'm guessing since it's the build backend rather than pdm proper that loads the dynamic version, there isn't a good way to handle it with this plugin such that it's fully integrated. The option I can think of, is if pdm-bump took its own options, which would be a bit duplicate of the build backends options to dynamically load the version. This would give it the info to load/save the version to the external location. It could basically mirror this poetry plugin in functionality:

https://github.com/monim67/poetry-bumpversion

**Comment by carstencodes** [comment]
This would be the same implementation as poetry-bumpversion - as you already mentioned - or in https://github.com/c4urself/bump2version .

It is actually on the far roadmap for 1.0 .

Im my personal opinion I consider this only an edge case.

Most development tools like sphinx etc. already use their own versioning file in their configuration.

I use PDM to be more PEP compliant. Most tools do that, too. If you transfer the sphinx configuration according to PEP 518 to pyproject.toml, then it looses its own version number and uses the one from pyproject.toml.

Modules can ask the stdlib for their version using `importlib.metadata`, and example can be found [here](https://github.com/carstencodes/pdm-bump/blob/cb76ba3eade8bf5303480c45332a46a4d4a3cf34/src/pdm_bump/__init__.py#L19). This does not work, if the package is editable.

This way only one version must be specifed.

According to PEP 621, the dynamic version can be declared as

```toml
dynamic = ["version"]

...
```

The interpretation of the dynamic behavior relies on the build backend. Hence the configuration is not unique.

I would support dynamic versions using the following constraints:

- The version is declared as dynamic in pyproject.toml
- The PEP 517 build backend is set to PDM
- The PDM configuration points to a file and not the SCM.
- The implementation will be based on `DynamicVersion` from pdm-pep517

If this is ok for you, I would plan it for pdm-bump 1.0.

**Comment by gazpachoking** [comment]
Yeah, that all sounds good to me. That's similar to how I was thinking, but I wasn't sure if it was good to tie it to a specific build backend and use the setting directly from that, or for pdm-bump to take its own settings specifying the file location (which would only become active if pyproject declared the version dynamic.)

**Comment by carstencodes** [comment]
Closed by #7 .

Planned Release for next version at the end of october

**Comment by carstencodes** [comment]
@gazpachoking Recent Release is 0.6.1 containing your changes. Thanks for supporting pdm-bump

**Comment by baggiponte** [comment]
Hi! I am using `pdm bump` to start a proper versioning strategy. I am also using a dynamic field:

```toml
[project]
dynamic = ["version"]

[tool.pdm.version]
source = "file"
path = "src/futura_aws/__init__.py"
```

However, whenever I try to `bump` I get the following error: what should I do?

```bash
pdm bump micro -v
Traceback (most recent call last):
  File "/Users/lucabaggi/.local/share/pipx/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/Users/lucabaggi/.local/share/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/core.py", line 259, in main
    return Core().main(args)
  File "/Users/lucabaggi/.local/share/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/core.py", line 191, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/Users/lucabaggi/.local/share/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/core.py", line 186, in main
    f(project, options)
  File "/Users/lucabaggi/.local/share/pipx/venvs/pdm/lib/python3.10/site-packages/pdm_bump/logging.py", line 197, in tracing_function
    return fun(*args, **kwargs)
  File "/Users/lucabaggi/.local/share/pipx/venvs/pdm/lib/python3.10/site-packages/pdm_bump/plugin.py", line 133, in handle
    selected_backend: Optional[_VersionSource] = self._select_backend(
  File "/Users/lucabaggi/.local/share/pipx/venvs/pdm/lib/python3.10/site-packages/pdm_bump/logging.py", line 197, in tracing_function
    return fun(*args, **kwargs)
  File "/Users/lucabaggi/.local/share/pipx/venvs/pdm/lib/python3.10/site-packages/pdm_bump/plugin.py", line 224, in _select_backend
    if backend.is_enabled:
  File "/Users/lucabaggi/.local/share/pipx/venvs/pdm/lib/python3.10/site-packages/pdm_bump/dynamic.py", line 103, in is_enabled
    return self.__config.meta_data.is_dynamic_version
  File "/Users/lucabaggi/.local/share/pipx/venvs/pdm/lib/python3.10/site-packages/pdm_bump/config.py", line 130, in is_dynamic_version
    return ConfigKeys().VERSION in self.__meta_data.dynamic
TypeError: EnumMeta.__call__() missing 1 required positional argument: 'value'
```

Thank you so much!

**Comment by carstencodes** [comment]
@baggiponte Already fixed by @cmarqu in #34 

v0.6.12 scheduled for tomorrow

**Comment by carstencodes** [comment]
@baggiponte @cmarqu Sorry for the delay. I was grounded in my bed due to a lumbago.

**Comment by cmarqu** [comment]
Ugh, get well soon, but don't rush it!

**Comment by baggiponte** [comment]
Thank you @carstencodes, but do not rush!

I naively tried `pdm self update pdm-bump` but it did not work. I resorted to uninstalling and reinstalling. How do you properly update plugins in pdm?

**Comment by carstencodes** [comment]
I actually use 

pip install --user --upgrade pdm-bump

Since this is the way I installed it
