### ISSUE TITLE
Way to print current version

### ISSUE THREAD

**Issue by gazpachoking** [carstencodes/pdm-bump#8]
Similar to `poetry version`, it would be nice if there was a way to print the current version. Especially nice in the case it's using the dynamic version loading machinery to discover the version. This would be useful in a release script, to e.g. create a tag with the current (or newly bumped) version.

**Comment by carstencodes** [comment]
Do you mean `pdm show --version`?

**Comment by gazpachoking** [comment]
I don't think so. That will only show the installed version of the built package, no? Not the live version from pyproject (or dynamic)

**Comment by gazpachoking** [comment]
> I don't think so. That will only show the installed version of the built package, no? Not the live version from pyproject (or dynamic)

Hmm. I might be wrong about this. At first glance `pdm show --version` is working how I want it. I'm struggling a little bit to understand _how_ though.

**Comment by gazpachoking** [comment]
I was indeed wrong. `pdm show --version` is showing me the info I want already. I didn't realize pdm was so tightly integrated with the pdm.pep517 builder. I wonder what happens with that command if I'm using a different builder...

**Comment by gazpachoking** [comment]
> I wonder what happens with that command if I'm using a different builder...

Just shows `None`. I guess that is reasonable.
